(setq package-selected-packages
      '(ace-jump-mode
        auto-complete
        auto-indent-mode
        diminish
        dired-details
        dropdown-list
        edit-server
        edit-server-htmlize
        edts
        erlang
        exec-path-from-shell
        fill-column-indicator
        flx-ido
        flycheck
        gitconfig-mode
        gitignore-mode
        god-mode
        haskell-mode
        httpcode
        ido-vertical-mode
        js2-mode
        ledger-mode
        magit
        markdown-mode
        multiple-cursors
        paredit
        projectile
        rainbow-mode
        restclient
        smex
        solarized-theme
        undo-tree
        use-package
        yaml-mode
        yasnippet))
